apiVersion: v1
kind: Namespace
metadata:
  name: gitops-pact-broker
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-pact-broker-operator-group
  namespace: gitops-pact-broker
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - gitops-pact-broker
---
